import { ExerciseDef, Profile, ProfileId, WorkoutId, WorkoutTemplate } from "./types";

// Tom: Full-body A/B, 3x per week, weken alternerend A-B-A / B-A-B.
// Dat komt neer op simpelweg elke sessie afwisselen tussen A en B.
const TOM_TEMPLATES: WorkoutTemplate[] = [
  {
    id: "A",
    name: "Workout A",
    exercises: [
      {
        id: "a-goblet-squat",
        name: "Goblet squat (dumbbell)",
        alternative: "Leg press",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 12,
        unit: "reps",
        restSeconds: 90,
        category: "squat",
        tip: "Houd de borst omhoog, knieën in lijn met de tenen, zak diep.",
      },
      {
        id: "a-db-bench-press",
        name: "Dumbbell bench press",
        alternative: "Chest press machine",
        defaultSets: 3,
        repsMin: 8,
        repsMax: 12,
        unit: "reps",
        restSeconds: 120,
        category: "horizontal-press",
        tip: "Schouderbladen samen, voeten stevig op de grond.",
      },
      {
        id: "a-db-shoulder-press",
        name: "Dumbbell shoulder press (zittend)",
        alternative: "Machine shoulder press",
        defaultSets: 3,
        repsMin: 8,
        repsMax: 12,
        unit: "reps",
        restSeconds: 90,
        category: "vertical-press",
        tip: "Core aangespannen, druk recht omhoog zonder hol te rug.",
      },
      {
        id: "a-bent-over-row",
        name: "Bent-over dumbbell row",
        alternative: "Seated cable row",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 12,
        unit: "reps",
        restSeconds: 90,
        category: "row",
        tip: "Rug recht, trek de ellebogen naar achteren langs het lichaam.",
      },
      {
        id: "a-rdl",
        name: "Romanian deadlift (dumbbell)",
        alternative: "Romanian deadlift (barbell)",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 12,
        unit: "reps",
        restSeconds: 120,
        category: "hinge",
        tip: "Lichte knikbuiging, zak met een rechte rug, voel de hamstrings.",
      },
      {
        id: "a-plank",
        name: "Plank",
        alternative: "Dead bug",
        defaultSets: 3,
        repsMin: 30,
        repsMax: 45,
        unit: "seconds",
        restSeconds: 45,
        category: "core",
        tip: "Rechte lijn van hoofd tot hielen, buik aangespannen.",
      },
    ],
  },
  {
    id: "B",
    name: "Workout B",
    exercises: [
      {
        id: "b-db-lunges",
        name: "Dumbbell lunges (per been)",
        alternative: "Leg press (unilateraal)",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 90,
        perSide: true,
        category: "lunge",
        tip: "Knie boven de enkel, romp rechtop, gecontroleerd zakken.",
      },
      {
        id: "b-lat-pulldown",
        name: "Lat pulldown / pull-up (assisted)",
        alternative: "Single-arm dumbbell row",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 12,
        unit: "reps",
        restSeconds: 90,
        category: "pulldown",
        tip: "Trek met de ellebogen naar beneden, borst vooruit.",
      },
      {
        id: "b-incline-press",
        name: "Incline dumbbell press",
        alternative: "Chest fly machine",
        defaultSets: 3,
        repsMin: 8,
        repsMax: 12,
        unit: "reps",
        restSeconds: 120,
        category: "horizontal-press",
        tip: "Bank op ~30°, schouderbladen samen, gecontroleerde beweging.",
      },
      {
        id: "b-lateral-raise",
        name: "Dumbbell lateral raise",
        alternative: "Cable lateral raise",
        defaultSets: 3,
        repsMin: 12,
        repsMax: 15,
        unit: "reps",
        restSeconds: 60,
        category: "lateral-raise",
        tip: "Lichte buiging in de ellebogen, til tot schouderhoogte, geen zwaai.",
      },
      {
        id: "b-bicep-curl",
        name: "Dumbbell bicep curl",
        alternative: "Cable curl",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 12,
        unit: "reps",
        restSeconds: 60,
        category: "curl",
        tip: "Ellebogen dicht bij het lichaam, geen momentum gebruiken.",
      },
      {
        id: "b-tricep-extension",
        name: "Overhead tricep extension (dumbbell)",
        alternative: "Cable pushdown",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 12,
        unit: "reps",
        restSeconds: 60,
        category: "triceps",
        tip: "Ellebogen dicht bij het hoofd, alleen de onderarm beweegt.",
      },
    ],
  },
];

// Ayse: focus billen, strakkere buik & algehele fitheid, 2-4x per week.
const AYSE_TEMPLATES: WorkoutTemplate[] = [
  {
    id: "A",
    name: "Dag A — Onderlichaam & billen",
    exercises: [
      {
        id: "ayse-a-abductor",
        name: "Abductor",
        alternative: "Cable hip abduction",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 60,
        startWeight: 45,
        category: "hip-isolation",
        tip: "Rugleuning stevig, beweeg gecontroleerd naar buiten.",
      },
      {
        id: "ayse-a-adductor",
        name: "Adductor",
        alternative: "Cable hip adduction",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 60,
        startWeight: 25,
        category: "hip-isolation",
        tip: "Beweeg de benen gecontroleerd naar binnen, geen zwaai.",
      },
      {
        id: "ayse-a-leg-extension",
        name: "Leg extension",
        alternative: "Dumbbell leg extension (zittend)",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 60,
        startWeight: 10,
        category: "leg-extension",
        tip: "Strek de knie volledig, zak gecontroleerd weer terug.",
      },
      {
        id: "ayse-a-goblet-squat",
        name: "Goblet squat",
        alternative: "Leg press",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 90,
        startWeight: 8,
        category: "squat",
        tip: "Houd de borst omhoog, zak tussen de benen door.",
      },
      {
        id: "ayse-a-bulgarian-split-squat",
        name: "Bulgarian split squat (per been)",
        alternative: "Reverse lunge (dumbbell)",
        defaultSets: 1,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 90,
        perSide: true,
        startWeight: 4,
        category: "lunge",
        tip: "Achterste voet op de bank, zak recht naar beneden.",
      },
      {
        id: "ayse-a-rdl",
        name: "Romanian deadlift (dumbbell)",
        alternative: "Romanian deadlift (barbell)",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 90,
        startWeight: 4,
        category: "hinge",
        tip: "Lichte knikbuiging, zak met een rechte rug.",
      },
      {
        id: "ayse-a-hip-thrust",
        name: "Hip thrust",
        alternative: "Glute bridge",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 90,
        startWeight: 10,
        category: "hip-thrust",
        tip: "Kin naar de borst, duw door de hielen, knijp de billen samen boven.",
      },
    ],
  },
  {
    id: "B",
    name: "Dag B — Bovenlichaam & buik",
    exercises: [
      {
        id: "ayse-b-lat-pulldown",
        name: "Lat pulldown",
        alternative: "Assisted pull-up",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 90,
        startWeight: 15,
        category: "pulldown",
        tip: "Trek met de ellebogen naar beneden, borst vooruit.",
      },
      {
        id: "ayse-b-low-row",
        name: "Low row",
        alternative: "Bent-over dumbbell row",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 90,
        startWeight: 10,
        category: "row",
        tip: "Trek de ellebogen naar achteren, borst vooruit.",
      },
      {
        id: "ayse-b-pectoral-fly",
        name: "Pectoral fly",
        alternative: "Dumbbell fly",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 60,
        startWeight: 5,
        category: "chest-fly",
        tip: "Lichte buiging in de ellebogen, beweeg gecontroleerd naar elkaar toe.",
      },
      {
        id: "ayse-b-shoulder-press",
        name: "Shoulder press",
        alternative: "Dumbbell shoulder press",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 90,
        startWeight: 5,
        category: "vertical-press",
        tip: "Core aangespannen, druk recht omhoog.",
      },
      {
        id: "ayse-b-lateral-raise",
        name: "Lateral raise",
        alternative: "Cable lateral raise",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 60,
        startWeight: 2,
        category: "lateral-raise",
        tip: "Lichte buiging in de ellebogen, til tot schouderhoogte.",
      },
      {
        id: "ayse-b-plank",
        name: "Plank",
        alternative: "Dead bug",
        defaultSets: 3,
        repsMin: 30,
        repsMax: 45,
        unit: "seconds",
        restSeconds: 45,
        category: "core",
        tip: "Rechte lijn van hoofd tot hielen, buik aangespannen.",
      },
      {
        id: "ayse-b-side-bend-standing",
        name: "Zijkant buik staand (per kant)",
        alternative: "Cable woodchop",
        defaultSets: 2,
        repsMin: 20,
        repsMax: 20,
        unit: "reps",
        restSeconds: 45,
        perSide: true,
        startWeight: 5,
        category: "core",
        tip: "Buig gecontroleerd opzij, voel de zijkant van je buik.",
      },
      {
        id: "ayse-b-side-bend-seated",
        name: "Zijkant buik zittend (per kant)",
        alternative: "Russian twist",
        defaultSets: 2,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 45,
        perSide: true,
        startWeight: 2.5,
        category: "core",
        tip: "Draai vanuit de romp, niet vanuit de armen.",
      },
      {
        id: "ayse-b-crunch-seated",
        name: "Crunch zittend, leunend op handen",
        alternative: "Cable crunch",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 45,
        bodyweight: true,
        category: "core",
        tip: "Rol de romp in, adem uit tijdens het omhoog komen.",
      },
      {
        id: "ayse-b-crunch-lying",
        name: "Crunch (liggend)",
        alternative: "Sit-up",
        defaultSets: 3,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 45,
        bodyweight: true,
        category: "core",
        tip: "Kin vrij van de borst, beweeg vanuit de buikspieren.",
      },
      {
        id: "ayse-b-leg-raises",
        name: "Leg raises",
        alternative: "Hanging knee raise",
        defaultSets: 2,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        restSeconds: 45,
        bodyweight: true,
        category: "core",
        tip: "Onderrug tegen de grond, benen gecontroleerd laten zakken.",
      },
    ],
  },
];

export const PROFILES: Record<ProfileId, Profile> = {
  tom: { id: "tom", label: "Tom", templates: TOM_TEMPLATES },
  ayse: { id: "ayse", label: "Ayse", templates: AYSE_TEMPLATES },
};

export const PROFILE_LIST: Profile[] = [PROFILES.tom, PROFILES.ayse];

export function getTemplate(profileId: ProfileId, templateId: WorkoutId): WorkoutTemplate {
  const template = PROFILES[profileId].templates.find((t) => t.id === templateId);
  if (!template) throw new Error(`Unknown template ${templateId} for profile ${profileId}`);
  return template;
}

export function getProfileTemplates(profileId: ProfileId): WorkoutTemplate[] {
  return PROFILES[profileId].templates;
}

export function getExerciseDef(exerciseId: string): ExerciseDef | undefined {
  for (const profile of PROFILE_LIST) {
    for (const template of profile.templates) {
      const exercise = template.exercises.find((e) => e.id === exerciseId);
      if (exercise) return exercise;
    }
  }
  return undefined;
}
